# Generated by Django 5.0.6 on 2024-06-25 19:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('79b7d20c-2f14-41ec-ba6c-132a16177125'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('79b7d20c-2f14-41ec-ba6c-132a16177125'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('79b7d20c-2f14-41ec-ba6c-132a16177125'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('79b7d20c-2f14-41ec-ba6c-132a16177125'), editable=False, primary_key=True, serialize=False),
        ),
    ]
