# Generated by Django 5.0.6 on 2024-06-25 19:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_commentlike_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19971c96-f517-49cb-bd67-50ffe91aaa8f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19971c96-f517-49cb-bd67-50ffe91aaa8f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19971c96-f517-49cb-bd67-50ffe91aaa8f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19971c96-f517-49cb-bd67-50ffe91aaa8f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
